version: '3.8'
services:
  frontend:
    build: frontend
    image: ghcr.io/${GITHUB_REPOSITORY}/frontend:latest
    ports:
      - 8501:8501
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
    restart: always
    networks:
      - app
    container_name: frontend
    
  backend:
    build: backend
    image: ghcr.io/${GITHUB_REPOSITORY}/backend:latest
    ports:
      - 8000:8000
    env_file:
      - .env
    volumes:
      - ./backend:/app
    restart: always
    networks:
      - app
    container_name: backend

networks:
  app:
    driver: bridge